# Generated by Django 5.2.7 on 2026-06-23 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnails/', verbose_name='Ảnh đại diện')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
